### ISSUE TITLE
Warn of obvious mistakes

### ISSUE THREAD

**Issue by nebulon42** [SecUSo/privacy-friendly-sudoku#10]
Great app. It would be nice if the app would mark obvious wrong entries (e.g. same number already exists in line, column or square) and thus warn the user about them. If you say this would not be desirable for everyone because of higher/lower difficulty it could be configurable and either be on or off by default.

**Comment by anarcat** [comment]
this should off by default, the app is already way more helpful than others by default...

**Comment by Yonjuni** [comment]
included. Closed #10
