### ISSUE TITLE
Unsolvable daily sudoku

### ISSUE THREAD

**Issue by matthee500** [SecUSo/privacy-friendly-sudoku#118]
I started a daily sudoku, after playing through the board, I realised that this specific daily game is unsolvable.

I tried sharing the game, however on import the program does correctly state that the game is unsolvable. Here is the link: https://sudoku.secuso.org/874630251195247836263581479342718695758396142916054783431865927629473518587129364

![Screenshot_20240408_122310_Sudoku.jpg](https://github.com/SecUSo/privacy-friendly-sudoku/assets/57432135/098e6976-a72f-40a9-9719-39e6f8fa01bd)

**Comment by mstammberger** [comment]
What about 
![Screenshot_20240408-142529_Sudoku_1](https://github.com/SecUSo/privacy-friendly-sudoku/assets/24432474/46c2443b-67b6-4d14-9321-9f71ea9cd9cf)
🙃

**Comment by mstammberger** [comment]
What about that:
![Screenshot_20240408-142529_Sudoku_1](https://github.com/SecUSo/privacy-friendly-sudoku/assets/24432474/a2fa9c06-3320-453e-a71d-8cf5f3b49426)
🙃
