### ISSUE TITLE
autosave games

### ISSUE THREAD

**Issue by anarcat** [SecUSo/privacy-friendly-sudoku#14]
because of #8, i recently saw my phone power down in the middle of a "difficult"-level game. when i restarted the phone, the game was gone!!! i was expecting the game to be automatically saved because there is a "continue" button on the main screen.

**Comment by Yonjuni** [comment]
Closed #14

**Comment by anarcat** [comment]
is this fixed or just refused?

**Comment by Yonjuni** [comment]
Fixed.
