### ISSUE TITLE
Add layout for 6"/7" tablets

### ISSUE THREAD

**Issue by mueller-ma** [SecUSo/privacy-friendly-sudoku#18]
Hi,
I have Sudoku v2.0.1 from fdroid running on a fire tablet 7" with Android 5.1.1.

- The grid has different border sizes, sometimes gray
- The Notes are pixelated
- Numbers on the buttons are too small
- Border of the buttons in the last row are too big

![screenshot](https://cloud.githubusercontent.com/assets/22525368/21697558/3521f320-d393-11e6-88a6-40d0cb85edd1.jpg)

**Comment by Yonjuni** [comment]
Closed #18

**Comment by mueller-ma** [comment]
Thanks!
