### ISSUE TITLE
Reseting a solved Sudoku does not clean up mistakes

### ISSUE THREAD

**Issue by Yonjuni** [SecUSo/privacy-friendly-sudoku#35]
1. Open Sudoku
2. Solve it with mistakes
3. Clear board
4. Mistakes still highlighted

![screenshot_2017-07-10-12-19-22](https://user-images.githubusercontent.com/7099812/28057584-b555c164-6620-11e7-8919-9f80f2d041ff.png)

**Comment by Kamuno** [comment]
seems to already be fixed but not closed. Could not reproduce issue with various different settings.
