### ISSUE TITLE
Main screen for play is broken

### ISSUE THREAD

**Issue by DarckCrystale** [SecUSo/privacy-friendly-sudoku#42]
Phone : Wiko Ozzy
Android version : 4.2.2
App version : 2.1.1
Language : French

### Scenario :
Open the application
Open a new 9*9 game

### Expected behaviour :
Game is playable

### Current behaviour :
Screen is broken
  
![screenshot_2018-01-05-00-59-11](https://user-images.githubusercontent.com/13867472/34590051-ad55050e-f1b4-11e7-8b72-528944e89909.png)

**Comment by Yonjuni** [comment]
@DarckCrystale Thanks for reporting. Could tell us you Android version and the language your device uses?

**Comment by DarckCrystale** [comment]
Sorry for the delay!

My ROM is in French, Android 4.2.2 (it's an old phone), App 2.1.1 :slightly_smiling_face:

**Comment by Yonjuni** [comment]
@DarckCrystale No problem, could you check if it persists in version 2.1.2?

**Comment by DarckCrystale** [comment]
I use F-Droid to manage my apps and there is no new version available :confused:
