### ISSUE TITLE
Allow creating personal Sudoku puzzles 

### ISSUE THREAD

**Issue by val24** [SecUSo/privacy-friendly-sudoku#45]
Hello,
I've been using your app for some time and really like it. I'd really like to be able to add personal puzzles in order to be able to solve them in your neat interface.
Thanks

**Comment by petermayer** [comment]
Thanks for the suggestion, we will keep it in mind for future versions.

**Comment by don46lh775b** [comment]
+1
would love to see this feature added

**Comment by don46lh775b** [comment]
+1
would love to see this feature added

**Comment by don46lh775b** [comment]
+1
would love to see this feature added

**Comment by don46lh775b** [comment]
+1
would love to see this feature added

**Comment by don46lh775b** [comment]
+1
would love to see this feature added

**Comment by don46lh775b** [comment]
+1
would love to see this feature added
