### ISSUE TITLE
This type of design should not happen? Can you guys fix this.

### ISSUE THREAD

**Issue by EdwinTrejo** [SecUSo/privacy-friendly-sudoku#50]
![Screenshot_20190820-231521_Sudoku](https://user-images.githubusercontent.com/7853982/63400158-d9eecb80-c3a0-11e9-9b20-d9d5533bc255.jpg)

**Comment by rrpriv** [comment]
You mean can design? Because it looks like fan. Nothing wrong with that.

**Comment by EdwinTrejo** [comment]
I am content if this is just a fan design.
