### ISSUE TITLE
ksenofobia CONTRIBUTING.md / xenophobic CONTRIBUTING.md

### ISSUE THREAD

**Issue by verdulo** [SecUSo/privacy-friendly-sudoku#52]
EO
Mi havas peton pri motivo de la jena regulo en [CONTRIBUTING.md](https://github.com/SecUSo/privacy-friendly-sudoku/blob/master/CONTRIBUTING.md#unwanted-changes):
>Unwanted Changes:
>New translations/languages

Bonvolu klarigi kiel tradukoj de la aplikaĵo kontraŭas al privateco de la uzanto.
Se vi plue decidos al rifuzi la kunfand-petojn #48 k #15, bonvolu konsideri ŝanĝi la titolon de la aplikaĵo al:
`Privacy Friendly Sudoku Only For English People`

——————————————————
EN (automatic translation)
I have a request for a reason for the following rule in [CONTRIBUTING.md](https://github.com/SecUSo/privacy-friendly-sudoku/blob/master/CONTRIBUTING.md#unwanted-changes):
> Unwanted Changes:
> New translations / languages

Please explain how translations of the application are contrary to the user's privacy.
If you further decide to reject the merge requests #48 & #15, please consider changing the title of the application to:
`Privacy Friendly Sudoku Only For English People`

——————————————————
DE (automatische Übersetzung)
Ich habe eine Anfrage nach einem Grund für die folgende Regel in [CONTRIBUTING.md](https://github.com/SecUSo/privacy-friendly-sudoku/blob/master/CONTRIBUTING.md#unwanted-changes):
>Unwanted Changes:
>New translations/languages

Bitte erläutern Sie, inwiefern Übersetzungen der Anwendung die Privatsphäre des Benutzers verletzen.
Wenn Sie die Zusammenführungsanforderungen #48 und #51 weiter ablehnen möchten, sollten Sie den Titel der Anwendung in Folgendes ändern:
`Privacy Friendly Sudoku Only For English People`

**Comment by Kamuno** [comment]
We used to accept merge requests with translations, but we had some instance, when somebody would intentionally inject false translations and hide insults in the translation. Since we are a very small team and do not have the time to check every single line with google translate we added this rule as a result. 

However, recently we have actually started accepting merge requests with translations despite the rule. See https://github.com/SecUSo/privacy-friendly-qr-scanner/pull/74

**Comment by verdulo** [comment]
EO
Mi tradukas (al Pola kaj Esperanto) multajn programojn, kaj mi neniam rimarkis, ke iu intence vandalismis iun tradukon, maltrafaj/malprecizaj tradukoj okazas, sed neniam insultoj. Bonvolu konsideri ŝanĝi tiun regulon kaj permesi tradukojn.

EN
I translate (to Polish and Esperanto) a lot of programs, and I never noticed that someone intentionally vandalized a translation, incorrect / inaccurate translations happen, but never insults. Please consider changing that rule and allowing translations.

**Comment by verdulo** [comment]
@Kamuno 
Ĉu eblas revizii la politikon pri tradukoj?
