### ISSUE TITLE
Update changelog for version 3.0.0

### ISSUE THREAD

**Issue by FranciscoPombal** [SecUSo/privacy-friendly-sudoku#58]
It would be nice if the changes of version 3.0.0 were mentioned/documented in the changelog file.

**Comment by Kamuno** [comment]
Please just check https://github.com/SecUSo/privacy-friendly-sudoku/releases
This is basically the changelog and is automatically up to date. I'm going to delete the CHANGELOG.md in the next revision.

**Comment by FranciscoPombal** [comment]
@Kamuno please reconsider this. Some kind of changelog document should always live in the .git repository itself. Otherwise you become unnecessarily tied in to GitHub as a hosting platform. If you wish to move to another hosting platform, you won't have the changelog information readily available.
