### ISSUE TITLE
Generates invalid sudokus with multiple solutions

### ISSUE THREAD

**Issue by avrohr** [SecUSo/privacy-friendly-sudoku#89]
On the highest difficulty level the app generates (almost?) always invalid puzzles with multiple solutions.

**Comment by Kamuno** [comment]
Can you give an example? The generated levels should only have one solution and as far as I can tell they do. That's how the generator works. 🤔

**Comment by Kamuno** [comment]
I just tested this multiple times and every Sudoku I tested had a unique solution...

**Comment by avrohr** [comment]
![image](https://user-images.githubusercontent.com/76944030/164512724-84e7cff5-67bd-4a0b-9811-6630f59d2184.png)

This is yesterdays daily Sudoku. It has 26 solutions.
I used this website: https://www.sudokuwiki.org/sudoku.htm
The Sudoku in question is encoded as: ........2.2..5.8.1......3..7.4.9........8541.....37...18....9....7..9...2...4..58

But I have tested a few of the generated ones as well and they come up with multiple solutions as well.

**Comment by Kamuno** [comment]
Your String is missing a 5
The correct encoding is: `........2.2..5.8.1......3..7.4.9........8541...5.37...18....9....7..9...2...4..58` or `000000002020050801000000300704090000000085410005037000180000900007009000200040058`.

You can easily extract the code via the "Share Sudoku"-Feature. I get only one Solution for this Sudoku.
![image](https://user-images.githubusercontent.com/11301924/164514325-8fb730bd-b4ef-490a-8792-a5293fb4c4e2.png)

**Comment by avrohr** [comment]
Well, sorry. I assume I also messed up the other puzzles I tested. Sorry for that. And thanks for the app!

**Comment by Kamuno** [comment]
No worries. You just had me shocked for a second 😅
